version: 2
jobs:
  build:
    docker:
      - image: roblinde/the-example-app-build-assets
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
      - run:
          name: Unit tests
          command: dotnet test TheExampleApp.Tests
      - run:
          name: Integration tests
          command: dotnet test TheExampleApp.IntegrationTests
      - run:
          name: Run app
          command: | 
            cd TheExampleApp
            dotnet run 
          background: true
      - run:
          name: Clone e2e tests
          command: | 
            git clone https://github.com/contentful/the-example-app-e2e-tests.git ./test/e2e
            cd test/e2e
      - restore_cache:
          keys:
            - package-v2-{{ checksum "./test/e2e/package.json" }}
            - package-v2
      - run: 
          name: Install e2e tests dependencies
          command: |
            cd test/e2e 
            npm i
      - save_cache:
          key: package-v2-{{ checksum "./test/e2e/package.json" }}
          paths:
            - ./test/e2e/node_modules      
      - run:
          name: Run e2e tests
          command: |
            cd test/e2e 
            node_modules/.bin/cypress run --project /root/project --env LANGUAGE=dotnet